### ISSUE TITLE
Current npm package broken

### ISSUE THREAD

**Issue by boronine** [mklabs/templatify#3]
The version of templatify in the npm registry depends on "hogan". The package "hogan" fails to install due to a [bug](https://github.com/twitter/hogan.js/issues/52) that has since been fixed. If you need the hogan dependency, you should depend on "hogan.js", which seems to be the new primary hogan package.

**Comment by mklabs** [comment]
Hey there,

Thanks for opening this ticket and the detail report (link to relevant hogan's issue). I'll update what needs to be asap.

**Comment by mklabs** [comment]
Done, the published version on master was the hogan branch, which is pretty unstable right now.

I'll probably kill off what was done on this branch, #4 is related.

Anyway, thanks for pointing this to my attention. broken packages on npm is likely not a very good thing =/
